// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfxyfsyleaoofdgzshcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmeHlmc3lsZWFvb2ZkZ3pzaGN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDAyNzEsImV4cCI6MjA2NTQxNjI3MX0.4_6zrZCUo-0L5J5RobAy5M_O9gbj29Yko1QRrzXK8vA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);